# Generated by Django 5.2.8 on 2025-11-25 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('enunciado', models.TextField()),
                ('especificacao_entrada', models.TextField(help_text='Explicação do formato de entrada')),
                ('especificacao_saida', models.TextField(help_text='Explicação do formato de saída')),
                ('restricoes', models.TextField(help_text='Ex: 1 <= N <= 100')),
                ('nivel', models.CharField(default='Júnior', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasoDeTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada', models.TextField(help_text='O dado que o sistema joga no código do aluno')),
                ('saida_esperada', models.TextField(help_text='A resposta exata que o código deve dar')),
                ('eh_exemplo', models.BooleanField(default=False)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_teste', to='api.problema')),
            ],
        ),
    ]
