# Generated by Django 5.2.8 on 2025-12-19 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('ano', models.IntegerField(help_text='Ano da prova (ex: 2025)')),
                ('fase', models.IntegerField(help_text='Fase da prova (1, 2, 3...)')),
                ('nivel', models.CharField(choices=[('PJ', 'Iniciação (PJ)'), ('J', 'Júnior'), ('1', 'Nível 1'), ('2', 'Nível 2'), ('S', 'Sênior')], default='J', max_length=2)),
                ('enunciado', models.TextField()),
                ('especificacao_entrada', models.TextField()),
                ('especificacao_saida', models.TextField()),
                ('restricoes', models.TextField()),
                ('time_limit', models.IntegerField(default=1000)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExemploDeProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_texto', models.TextField()),
                ('saida_texto', models.TextField()),
                ('explicacao', models.TextField(blank=True, help_text='Texto explicativo didático', null=True)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplos', to='api.problema')),
            ],
        ),
        migrations.CreateModel(
            name='CasoDeTeste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtarefa_id', models.IntegerField(blank=True, null=True)),
                ('caminho_entrada', models.CharField(max_length=500)),
                ('caminho_saida', models.CharField(max_length=500)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos_teste', to='api.problema')),
            ],
        ),
        migrations.CreateModel(
            name='Submissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.TextField()),
                ('linguagem', models.CharField(default='python', max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('tempo', models.FloatField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.problema')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
